title: Vincent 'Philaeux' Lamotte
description: > # this means to ignore newlines until "baseurl:"
  Blog personnel de Vincent 'Philaeux' Lamotte
url: https://philaeux.github.io
baseurl: # the sub-path of your site, e.g. /blog/

disqus_shortname: # leave empty if you don't want comments
google_analytics: false #if set to "true" modify the google_analytycs.html, set to false otherwise

# Links settings
links:
  - name:         Index
    url:          /
  - name:         Archives
    url:          /archives
    external:     false
  - name:         À propos
    url:          /about
    external:     false

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
